name: Windows EXE Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Go to haxelib folder
        shell: bash
        run: |
          cd ~/haxelib

      - name: Cache Windows Build
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\haxelib
            C:\Users\runneradmin\.lime
            export
          key: windows-${{ runner.os }}-haxe4.2.5-${{ hashFiles('**/Project.xml', '**/*.hxml', '**/haxelib.json') }}
          restore-keys: |
            windows-${{ runner.os }}-haxe4.2.5-
            windows-${{ runner.os }}-

      - name: Install dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hxcpp --quiet
          haxelib install flixel-addons --quiet

      - name: Setup Lime
        run: |
          haxelib run lime setup --quiet

      - name: Build Windows EXE
        run: |
         haxelib run lime build windows

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: export/windows/bin/
